# Site Settings
title: My Resume
url: 'https://dhruvdt.github.io/'
#baseurl: '/profile' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Dhruv Tyagi
tagline: Android Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'A forward thinking developer offering more than one years and ten months of experience in building, integrating, testing and supporting Android applications for mobile and tablet devices on the Android platform.'

#sidebar links
email: dhruvtyagi88@gmail.com
phone: 9910634752
#website: blog.webjeda.com #do not add http://
linkedin: dhruvdt
github: Dhruvdt
twitter: 'users/5614644/dhruv-tyagi'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
